//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleDeneme.localhost {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="localhost.ISiparis")]
    public interface ISiparis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiparis/GetSiparisBilgileri", ReplyAction="http://tempuri.org/ISiparis/GetSiparisBilgileriResponse")]
        ROP.Commons.entSiparis GetSiparisBilgileri();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiparis/GetSiparisBilgileri", ReplyAction="http://tempuri.org/ISiparis/GetSiparisBilgileriResponse")]
        System.Threading.Tasks.Task<ROP.Commons.entSiparis> GetSiparisBilgileriAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISiparisChannel : ConsoleDeneme.localhost.ISiparis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiparisClient : System.ServiceModel.ClientBase<ConsoleDeneme.localhost.ISiparis>, ConsoleDeneme.localhost.ISiparis {
        
        public SiparisClient() {
        }
        
        public SiparisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SiparisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiparisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiparisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ROP.Commons.entSiparis GetSiparisBilgileri() {
            return base.Channel.GetSiparisBilgileri();
        }
        
        public System.Threading.Tasks.Task<ROP.Commons.entSiparis> GetSiparisBilgileriAsync() {
            return base.Channel.GetSiparisBilgileriAsync();
        }
    }
}
