//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROPv1.sezerwcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="entSiparis", Namespace="http://schemas.datacontract.org/2004/07/ROP.Commons")]
    [System.SerializableAttribute()]
    public partial class entSiparis : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departmanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string garsonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int masaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string siparisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int siparisIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departman {
            get {
                return this.departmanField;
            }
            set {
                if ((object.ReferenceEquals(this.departmanField, value) != true)) {
                    this.departmanField = value;
                    this.RaisePropertyChanged("departman");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string garson {
            get {
                return this.garsonField;
            }
            set {
                if ((object.ReferenceEquals(this.garsonField, value) != true)) {
                    this.garsonField = value;
                    this.RaisePropertyChanged("garson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int masa {
            get {
                return this.masaField;
            }
            set {
                if ((this.masaField.Equals(value) != true)) {
                    this.masaField = value;
                    this.RaisePropertyChanged("masa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string siparis {
            get {
                return this.siparisField;
            }
            set {
                if ((object.ReferenceEquals(this.siparisField, value) != true)) {
                    this.siparisField = value;
                    this.RaisePropertyChanged("siparis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int siparisId {
            get {
                return this.siparisIdField;
            }
            set {
                if ((this.siparisIdField.Equals(value) != true)) {
                    this.siparisIdField = value;
                    this.RaisePropertyChanged("siparisId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="sezerwcf.ISiparis")]
    public interface ISiparis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiparis/GetSiparisBilgileri", ReplyAction="http://tempuri.org/ISiparis/GetSiparisBilgileriResponse")]
        ROPv1.sezerwcf.entSiparis GetSiparisBilgileri();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiparis/GetSiparisBilgileri", ReplyAction="http://tempuri.org/ISiparis/GetSiparisBilgileriResponse")]
        System.Threading.Tasks.Task<ROPv1.sezerwcf.entSiparis> GetSiparisBilgileriAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISiparisChannel : ROPv1.sezerwcf.ISiparis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiparisClient : System.ServiceModel.ClientBase<ROPv1.sezerwcf.ISiparis>, ROPv1.sezerwcf.ISiparis {
        
        public SiparisClient() {
        }
        
        public SiparisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SiparisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiparisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiparisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ROPv1.sezerwcf.entSiparis GetSiparisBilgileri() {
            return base.Channel.GetSiparisBilgileri();
        }
        
        public System.Threading.Tasks.Task<ROPv1.sezerwcf.entSiparis> GetSiparisBilgileriAsync() {
            return base.Channel.GetSiparisBilgileriAsync();
        }
    }
}
